# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './interface/MyWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1135, 605)
        MainWindow.setStyleSheet("background-color: rgb(61, 56, 70);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Input_count_fib_entry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Input_count_fib_entry.setGeometry(QtCore.QRect(20, 80, 441, 121))
        self.Input_count_fib_entry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 63 13pt \"URW Bookman\";\n"
"gridline-color: rgb(0, 0, 0);")
        self.Input_count_fib_entry.setPlainText("")
        self.Input_count_fib_entry.setObjectName("Input_count_fib_entry")
        self.Get_fib_arr_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Get_fib_arr_btn.setGeometry(QtCore.QRect(20, 210, 271, 51))
        self.Get_fib_arr_btn.setStyleSheet("font: 25 oblique 11pt \"Umpush\";\n"
"background-color: rgb(255, 255, 255);\n"
"font: 63 13pt \"URW Gothic\";")
        self.Get_fib_arr_btn.setObjectName("Get_fib_arr_btn")
        self.Input_arr_entry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Input_arr_entry.setGeometry(QtCore.QRect(630, 80, 471, 121))
        self.Input_arr_entry.setStyleSheet("font: 63 13pt \"URW Bookman\";\n"
"background-color: rgb(255, 255, 255);")
        self.Input_arr_entry.setObjectName("Input_arr_entry")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(100, 10, 351, 61))
        self.label_1.setStyleSheet("background-color: rgb(61, 56, 70);\n"
"color: rgb(153, 193, 241);\n"
"font: 75 33pt \"Ubuntu\";")
        self.label_1.setObjectName("label_1")
        self.Output_fib_arr_entry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Output_fib_arr_entry.setGeometry(QtCore.QRect(20, 280, 471, 281))
        self.Output_fib_arr_entry.setStyleSheet("font: 63 13pt \"URW Bookman\";\n"
"background-color: rgb(255, 255, 255);")
        self.Output_fib_arr_entry.setObjectName("Output_fib_arr_entry")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(690, 10, 381, 61))
        self.label_2.setStyleSheet("background-color: rgb(61, 56, 70);\n"
"color: rgb(153, 193, 241);\n"
"font: 75 33pt \"Ubuntu\";")
        self.label_2.setObjectName("label_2")
        self.Filter_arr_max_alloc_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Filter_arr_max_alloc_btn.setGeometry(QtCore.QRect(630, 210, 411, 51))
        self.Filter_arr_max_alloc_btn.setAcceptDrops(False)
        self.Filter_arr_max_alloc_btn.setStyleSheet("font: 25 oblique 11pt \"Umpush\";\n"
"background-color: rgb(255, 255, 255);\n"
"font: 63 13pt \"URW Gothic\";")
        self.Filter_arr_max_alloc_btn.setObjectName("Filter_arr_max_alloc_btn")
        self.Output_filter_arr_entry = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Output_filter_arr_entry.setGeometry(QtCore.QRect(630, 410, 471, 151))
        self.Output_filter_arr_entry.setStyleSheet("font: 63 13pt \"URW Bookman\";\n"
"background-color: rgb(255, 255, 255);")
        self.Output_filter_arr_entry.setObjectName("Output_filter_arr_entry")
        self.Filter_arr_accurate_alloc_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Filter_arr_accurate_alloc_btn.setGeometry(QtCore.QRect(630, 270, 411, 51))
        self.Filter_arr_accurate_alloc_btn.setAcceptDrops(False)
        self.Filter_arr_accurate_alloc_btn.setStyleSheet("font: 25 oblique 11pt \"Umpush\";\n"
"background-color: rgb(255, 255, 255);\n"
"font: 63 13pt \"URW Gothic\";")
        self.Filter_arr_accurate_alloc_btn.setObjectName("Filter_arr_accurate_alloc_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1135, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.Exit = QtWidgets.QMenu(self.menubar)
        self.Exit.setObjectName("Exit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.Clear_action = QtWidgets.QAction(MainWindow)
        self.Clear_action.setIconVisibleInMenu(True)
        self.Clear_action.setShortcutVisibleInContextMenu(True)
        self.Clear_action.setObjectName("Clear_action")
        self.Quit = QtWidgets.QAction(MainWindow)
        self.Quit.setObjectName("Quit")
        self.menu.addAction(self.Clear_action)
        self.Exit.addAction(self.Quit)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.Exit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Input_count_fib_entry.setPlaceholderText(_translate("MainWindow", "Введите кол-во чисел Фибоначчи для генерации (до 90 чисел)"))
        self.Get_fib_arr_btn.setText(_translate("MainWindow", "Вывести полученный массив"))
        self.Input_arr_entry.setPlaceholderText(_translate("MainWindow", "Введите массив для фильтрации"))
        self.label_1.setText(_translate("MainWindow", "Первое задание"))
        self.Output_fib_arr_entry.setPlaceholderText(_translate("MainWindow", "Здесь будут выведены числа Фибоначчи"))
        self.label_2.setText(_translate("MainWindow", "Второе задание"))
        self.Filter_arr_max_alloc_btn.setText(_translate("MainWindow", "Отфильтровать массив (выделение с запасом)"))
        self.Output_filter_arr_entry.setPlaceholderText(_translate("MainWindow", "Здесь будет выведен отфильтрованный массив"))
        self.Filter_arr_accurate_alloc_btn.setText(_translate("MainWindow", "Отфильтровать массив (точное выделение)"))
        self.menu.setTitle(_translate("MainWindow", "Инструменты"))
        self.Exit.setTitle(_translate("MainWindow", "Выход"))
        self.action.setText(_translate("MainWindow", "Сокрыть текст"))
        self.action_2.setText(_translate("MainWindow", "Извлечь текст"))
        self.Clear_action.setText(_translate("MainWindow", "Очистить поля"))
        self.Quit.setText(_translate("MainWindow", "Выход"))
